/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAdd extends SimpleNode {
    public ASTAdd(int id) {
        super(id);
    }

    public ASTAdd(eg2 p, int id) {
        super(p, id);
    }

//  SimpleNode reduce() {
//    SimpleNode leftSubExpr = jjtGetChild(0);
//    SimpleNode rightSubExpr = jjtGetChild(1);
//
//    SimpleNode reducedLeftSubExpr = leftSubExpr.reduce(); // Recursively reduce the left sub expression
//    SimpleNode reducedRightSubExpr = rightSubExpr.reduce(); // Recursively reduce the right sub expression
//
//    if ( reducedLeftSubExpr instanceof ASTInteger && reducedRightSubExpr instanceof ASTInteger ) { // case that can be reduced
//      int sum = reducedLeftSubExpr.getInt() + reducedRightSubExpr.getInt();
//      return new ASTInteger(sum);
//    } else { // case that cannot be reduced
//      jjtAddChild(reducedLeftSubExpr, 0);
//      jjtAddChild(reducedRightSubExpr, 1);
//      return this;
//    }
//  }

}
/* JavaCC - OriginalChecksum=76da0ba34f500bf20909789c6322debb (do not edit this line) */
