/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMult extends SimpleNode {
    public ASTMult(int id) {
        super(id);
    }

    public ASTMult(eg2 p, int id) {
        super(p, id);
    }

    @Override
    public String toString() {
        return "*";
    }

}
/* JavaCC - OriginalChecksum=23e5ea8eeb4084ecb355a7af88d75f7d (do not edit this line) */
