/* Generated By:JavaCC: Do not edit this line. eg2TreeConstants.java Version 7.0.6 */
public interface eg2TreeConstants {
    public int JJTSTART = 0;
    public int JJTVOID = 1;
    public int JJTADD = 2;
    public int JJTMULT = 3;
    public int JJTMYID = 4;
    public int JJTINTEGER = 5;


    public String[] jjtNodeName = {
            "Start",
            "void",
            "Add",
            "Mult",
            "MyID",
            "Integer",
    };
}
/* JavaCC - OriginalChecksum=5a355ee2ce55dab38861aa0013a1b9c4 (do not edit this line) */
