/* Generated By:JavaCC: Do not edit this line. eg2TreeConstants.java Version 7.0.6 */
public interface eg2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMULT = 4;
  public int JJTDIV = 5;
  public int JJTMOD = 6;
  public int JJTMYID = 7;
  public int JJTINTEGER = 8;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Sub",
    "Mult",
    "Div",
    "Mod",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=2083308213121ac3783c75b36bcd9800 (do not edit this line) */
